blank_issues_enabled: false
contact_links:
  - name: Circlecropqzboat Community Support
    url: https://github.com/liqs91/circlecropqzboat/issues
    about: Please ask and answer questions here.
  - name: Circlecropqzboat Documentation
    url: https://github.com/liqs91/circlecropqzboat#readme
    about: Please check out the documentation here.
